name: Deploy to WordPress.org

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    name: New Release${{ github.event_name == 'workflow_dispatch' && ' (dry run)' || '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get plugin version
        id: get-version
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            echo "version=$(awk '/Stable tag:   /{print $NF}' readme.txt)" >> $GITHUB_OUTPUT
          else
            VERSION="${GITHUB_REF#refs/tags/}"
            VERSION="${VERSION#v}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: WordPress plugin deploy
        id: wporg-deployment
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
          dry-run: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ github.event.repository.name }}
          VERSION: ${{ steps.get-version.outputs.version }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.wporg-deployment.outputs.zip-path }}